apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: azure-store
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    app: order-service
